config:
  classroom:hostname: lf2607
  classroom:title: lf2607
  classroom:zone: sg-sin1
  classroom:plan: STARTER-4xCPU-8GB
  # UpCloud Debian 13 server template UUID
  classroom:serverTemplateStorage: 01000000-0000-4000-8000-000020080100
  classroom:diskGiB: "40"
  classroom:metadata: "true"
  classroom:firewall: "false"
  classroom:sourceIpFiltering: "true"
  classroom:timezone: UTC
  classroom:bootOrder: disk
  classroom:nicModel: virtio
  classroom:videoModel: vga
  classroom:sshPublicKeyNames:
    - yubikey_25_939_134
    - salt_ssh
  classroom:loginUser: root
  classroom:ipv4ReverseDnsHostname: lf2607.kolamayermakers.org
  classroom:cloudflareAccountId: 11df27489df0a87ad0108ded43ecf9bc
  classroom:cloudflareZoneName: kolamayermakers.org
  classroom:canonicalDnsRecordName: lf2607.kolamayermakers.org
  classroom:dnsRecordTtl: "1"
  classroom:dnsRecordProxied: "false"
  upcloud:token:
    secure: AAABAC07fjr+k9YkiP7F74IhPUMSRhifVlPhGsRGdcpVS+pZHFbMrcBu+geIVLXhhW55x1Dots5uW60pa9yt
  cloudflare:apiToken:
    secure: AAABAEsI8zSKtj/tnHwsURNQLWWoQ3iPfMJRy1Za0i1FA5T5HS366MNiC+JIIOm1hvulI8FMx//doL/+Fwffu1FtOUFsicPWrophyiJKi5ZihdLsDQ==
